### ISSUE TITLE
Ajouter des classes ``fr-btns-group--m…` pour contrôler les marges des boutons dans un `fr-btns-group`

### ISSUE THREAD

**Issue by christophehenry** [GouvernementFR/dsfr#1016]
**Si votre suggestion concerne un composant existant, merci de décrire le problème rencontré de façon claire et concise**

Les `.fr-btn` dans un `.fr-btns-group` ont une marge basse par défaut. À l'heure actuelle, la seule façon de surcharger cette marge, c'est d'appliquer `.fr-mb-0` sur tous les boutons individuellement ou écrire une règle CSS. 

**Si vous avez déjà identifié une correction**
Avoir une règle `.fr-btns-group--m{t,r,b,l,y,x}-{0,1,…}v` permettant de surcharger les marges de tous les boutons en même temps serait pratique.

**Contexte & informations complémentaires**
Il arrive que le composant `.`fr-btns-group` ne soit pas seul sur son bloc mais partage l'espace avec d'autres éléments. Dans un tel cas, celui-ci impose sa marge basse.

**Comment by keryanS** [comment]
Bonjour,

Les marges entre les boutons d'un groupe sont de 16px. Cette valeur est fixe et définie par l'UI. Elle est identique à la marge appliquée sur les <p>.

Dans quel contexte souhaitez-vous modifier cette marge entre les boutons ? Et sur quelle taille de boutons ?

**Comment by keryanS** [comment]
Je vois, dans ce cas, pourquoi ne pas utiliser directement un utilitaire d'espacement sur le groupe de bouton ? 

Par exemple :`fr-mb-n4v` pour retirer la marge

**Comment by christophehenry** [comment]
Ah yes, pas bête, ça fonctionne.
