### ISSUE TITLE
Lien non fonctionnel sur la page d’accueil

### ISSUE THREAD

**Issue by l-vincent-l** [GouvernementFR/dsfr#1029]
###  Documentation associée
Sur la page d’accueil le bouton `Prendre en main le Système de Design` renvoie vers une page 

https://github.com/user-attachments/assets/00768892-cc44-4126-b73b-38dfa1aa3996

Merci de fournir les différentes sources et recherches qui pourraient appuyer cette suggestion.

**Comment by keryanS** [comment]
Bonjour,

Il doit sans doute rester du cache sur votre navigateur car ce lien à été corrigé récemment.
Essayez en navigation privée, cela devrait rediriger vers [https://www.systeme-de-design.gouv.fr/prise-en-main-et-perimetre/](https://www.systeme-de-design.gouv.fr/prise-en-main-et-perimetre/)

Je vous laisse fermer ce ticket, si cela fonctionne.

Keryan, pour l'équipe DSFR

**Comment by l-vincent-l** [comment]
Effectivement, je ferme le ticket.
