### ISSUE TITLE
Accessibilité du composant Segmented Control

### ISSUE THREAD

**Issue by Alezco** [GouvernementFR/dsfr#1059]
**Si votre suggestion concerne un composant existant, merci de décrire le problème rencontré de façon claire et concise**
Sur le composant [Segmented Control](https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants/controle-segmente/), si aucun élément n'est sélectionné par défaut, le focus au clavier n'est pas visible.

**Décrivez le comportement souhaité**
Si aucune option n'est sélectionnée par défaut sur le Segmented Control (par exemple dans un état initial de formulaire), il faudrait que le focus au clavier (quand on appuie sur Tab) soit visible à l'écran.

**Si vous avez déjà identifié une correction**
2 correctifs sont possibles :
- on met dans la spécification du composant qu'il ne peut pas être dans un état avec aucun élément sélectionné
- on ajoute une classe CSS pour que le focus soit visible en cas de navigation au clavier

**Contexte & informations complémentaires**
![Capture d’écran du 2024-12-09 15-28-09](https://github.com/user-attachments/assets/932c9cb7-fe76-4174-835e-c1b49a92c927)
Sur cette capture d'écran, aucun élément n'est sélectionné par défaut, et aucun focus n'est visible

**Comment by keryanS** [comment]
Bonjour,

Le contrôle segmenté doit obligatoirement avoir un élément sélectionné par défaut, comme indiqué dans la description du composant dans la documentation : 
"Le composant "Contrôle segmenté" permet à l'utilisateur de choisir un type de vue parmi plusieurs options d'affichage disponibles, mutuellement exclusives avec **une valeur sélectionnée par défaut.**"

Il pourrait être intéressant de le préciser dans la partie "Usage".

Keryan, pour l'équipe DSFR
