### ISSUE TITLE
Feature request : add component for the events

### ISSUE THREAD

**Issue by jdlom** [GouvernementFR/dsfr#106]
Hi,

Amazing work ! 

It would be nice to have a special component for the events : 

Something like that ( from the _gendarmerie_ website ) :

<img width="204" alt="62ITxX1lJL" src="https://user-images.githubusercontent.com/8641271/140650674-10e39e68-b704-4a95-a9b0-248c8a44715f.png">

https://www.gendarmerie.interieur.gouv.fr/recrutement

**Comment by jchourdeaux** [comment]
Hi @jdlom , hope you're doing well (and sorry for the delay).

I add this specific idea to enrich another UX story in our backlog, to study the use case !

Thanx for your suggestion. 

Kind regards.
