### ISSUE TITLE
Feature request : add component for accessibility

### ISSUE THREAD

**Issue by jdlom** [GouvernementFR/dsfr#107]
I know the subject is complicated but it would be great if you could implement some basic feature (but useful)
to increase the accessibility

I like the approach found on the website https://www.civils.defense.gouv.fr/.

You can find an accessibility component : 

![PZCqfNSAaT](https://user-images.githubusercontent.com/8641271/140651448-40101c9f-018a-4e28-85a6-2482b62be9e1.gif)

**Comment by jchourdeaux** [comment]
Hi @jdlom ,
thanks for your contribution. 

At the moment, we don't plan to study this feature for two main reasons : first all our core and component take accessibility criterias into account by default (color contrast, line-heights, no justify). We know that everything is not perfect, but we're really trying to enhance the DSFR that way. 
Moreover people often use their own tool (voice readers, zoom text , and so on) to fit their needs and override the default settings...
But we keep the idea in mind . 
Many thanx. Kind regards
