### ISSUE TITLE
[NPM registry] Version 1.2.2 not published

### ISSUE THREAD

**Issue by comxd** [GouvernementFR/dsfr#161]
Regarding the [changelog](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/845905926/Version+1.2#Version-1.2.2-%E2%80%94-29-novembre-2021), a new 1.2.2 version seem to be available but not published on the NPM registry?

**Comment by jchourdeaux** [comment]
Hi @comxd , hope you're doing well!
Actually, only the Sketch lib is in 1.2.2. 
Both Figma and code are in 1.2.1 (we just changed the title to make it clearer than it was) . 
Kind regards
