### ISSUE TITLE
Add mastodon icon

### ISSUE THREAD

**Issue by bzg** [GouvernementFR/dsfr#235]
Hi! Some French public agencies are using mastodon, e.g. https://mastodon.social/@Mi_NumEco_Gouv

We also consider creating a mastodon account for https://code.gouv.fr.

For now, the mastodon icon (see [this version](https://fontawesome.com/v5/icons/mastodon?s=brands)) is not available and agencies have to use a ad hoc one (see https://ecoresponsable.numerique.gouv.fr/contact/).

It would be great to use a mastodon icon directly from dsfr.

**Comment by jchourdeaux** [comment]
Hi @bzg 

Sure, we'll add it to the fonticon as soon as possible, especially since it's available on remixicon .

Kind regards

**Comment by bzg** [comment]
Thank you!

**Comment by bzg** [comment]
Hi! I thought this was planned for 1.5 - is it delayed to 1.6?  Thanks!

**Comment by jchourdeaux** [comment]
Hi @bzg , 
fr-icon-mastodon-fill and fr-icon-mastodon-line had been added to the icon utility in the last version 1.5. Did you find it ?

**Comment by bzg** [comment]
Hi! I just did, see this [commit](https://git.sr.ht/~etalab/code.gouv.fr/log?from=a708489af0ba4f1406f3b767a68fe2a814e3d521#log-a708489af0ba4f1406f3b767a68fe2a814e3d521). Thanks for the heads up!
