### ISSUE TITLE
Awesome :-)

### ISSUE THREAD

**Issue by piotr-yuxuan** [GouvernementFR/dsfr#24]
Bonjour, quelques questions ou suggestions:

- Would you consider just even a short, self-contained English-based introduction to this system?
- Would you consider some demo page like gouvernementfr.github.io/dsfr?

**Comment by jchourdeaux** [comment]
Hi @piotr-yuxuan , 

i hope you're doing well. 
- For the english based intro, we'll have a look on that point (you're the first one to ask it ;-) ) .
- Concerning the online demo , we're working on at the moment so it will arrive soon (we hope).
Thanks a lot for your feedback !
Kind regards
