### ISSUE TITLE
Points de ruptures marges

### ISSUE THREAD

**Issue by titouandk** [GouvernementFR/dsfr#263]
Bonjour,

Il semblerait que les points de ruptures pour les marges ne sont disponibles que pour le breakpoint `md`.

![Sans titre](https://user-images.githubusercontent.com/5413308/159927180-c70d9f1a-c8cb-4ca3-9b8d-dd11aaa7e31d.png)

En effet, le code ci-dessous fonctionne bien (pour avoir une marge à partir de `md`) :
`fr-pl-0 fr-pl-md-8w`
(Je spécifie que le padding left est 0 afin de retirer les marges par défaut)

Mais ce code ne fonctionne pas (pour avoir une marge à partir de `sm`) :
`fr-pl-0 fr-pl-sm-8w`

Est-ce un comportement attendu ?
Y aura-t-il un support de tous les breakpoints pour les marges (padding/margin) à l'avenir ?

Je vous remercie

**Comment by jchourdeaux** [comment]
Bonjour @titouandk , 
Effectivement nous n'avons mis qu'un seul bp pour des raisons de poids. 
Le récent split des utilities va probablement nous permettre de reprendre le sujet plus simplement. 
C'est donc prévu ;)

**Comment by christophehenry** [comment]
Nous sommes presque 2 ans plus tard et ce problème existe toujours. Pouvez-vous rouvrir cette issue ?
