### ISSUE TITLE
Scroll intempestif sur lien d'ouverture d'un accordéon

### ISSUE THREAD

**Issue by thibault** [GouvernementFR/dsfr#271]
Je rencontre un problème de comportement lors d'une utilisation du composant accordéon avec un bouton supplémentaire.

Ma version du dsfr : 1.4.0.

## Description du problème

Dans les tréfonds de ma page se trouve un accordéon tout à fait standard, et qui fonctionne correctement.

Toutefois, j'ai besoin d'ajouter plus haut une ancre qui permet d'aller directement à une section d'accordéon spécifique.

D'après la doc :

> L'élement fr-accordion est une implémentation du système de collapse, il peut vivre de manière indépendante dans le code, et ainsi s’ouvrir et se fermer au clic.

J'ai donc ajouté un lien `a` avec les bons attributs.

## Comportement attendu

Quand je clique sur la première ancre, le navigateur scrolle jusqu'à la bonne section d'accordéon et elle s'ouvre. Quand je clique sur l'entête de section, celle-ci se referme.

## Comportement constaté

Quand je clique sur la première ancre, le navigateur scrolle et la section s'ouvre correctement. En revanche, quand je clique sur l'entête, la section se referme **mais** le navigateur scrolle intempestivement jusqu'à l'ancre se trouvant en haut de page.

## Comment reproduire le problème

Je reproduis le problème sur la page d'exemple issue du code npm du dsfr.

`node_modules/@gouvfr/dsfr/example/component/accordion/index.html`

```html
<!-- Ligne ajoutée en haut de la page -->
<a href="#accordion-113" aria-expanded="false" aria-controls="accordion-113">Cliquez pour voir l'élément d'accordéon approprié</a>

<!-- Plus bas -->
<div class="fr-accordions-group">
    …
    <section class="fr-accordion">
        <h3 class="fr-accordion__title">
            <button class="fr-accordion__btn" aria-expanded="false" aria-controls="accordion-113">Intitulé accordéon</button>
        </h3>
        <div class="fr-collapse" id="accordion-113">
            <!-- données de test -->
            <div>
                <h4 class="fr-h4">Contenu </h4>
                <p>…</p>
            </div>
        </div>
    </section>
</div>
```

Je ne sais pas si mon utilisation est tout simplement incorrecte ou s'il s'agit d'un bug. Au plaisir d'en discuter.

**Comment by lab9fr** [comment]
Bonjour Thibault, 

Désolé pour le temps de latence dans la réponse.

Je pense que le problème provient de la récupération du focus sur le bouton à la fermeture de l'accordéon. C'est une obligation d'accessibilité, à la fermeture de l'accordéon, le focus revient sur le bouton qui peut ouvrir l'accordéon. En l'occurrence, le premier. qui est ici votre lien.

Nous pourrions rajouter un attribut permettant de déterminer quel élément doit reprendre le focus.
Est-ce que cette solution pourrait vous aider ?

**Comment by thibault** [comment]
Hello @lab9fr,

> Désolé pour le temps de latence dans la réponse.

Je n'attendais plus de réponse :)

> Je pense que le problème provient de la récupération du focus sur le bouton à la fermeture de l'accordéon.

Effectivement, je n'avais pas pensé à ce mécanisme.

> Nous pourrions rajouter un attribut permettant de déterminer quel élément doit reprendre le focus.

Assurément. Toutefois, je ne sais pas dans quelle mesure mon cas d'usage est vraiment très spécifique ni si ça vaut le coup de complexier le dsfr juste pour ça. Est-ce que simplement privilégier la sélection du bouton à l'intérieur de l'élément `fr-accordion` contenant le `fr-collapse` ne ferait-pas l'affaire ?

**Comment by lab9fr** [comment]
Hello @thibault,

Je vais créer un ticket pour que l'on explore les possibilités dans ce sens. Actuellement, ce transfert de focus se fait de manière plus générique au niveau de `Disclosure`, classe abstraite. Mais on doit pouvoir mettre quelque chose en place.

Merci du retour !

**Comment by lab9fr** [comment]
corrigé dans la 1.10.1
