### ISSUE TITLE
Reproposer la couleur de fond correspondant aux tableaux de la v1.0

### ISSUE THREAD

**Issue by bzg** [GouvernementFR/dsfr#304]
J'avais soumis cette proposition en novembre dernier: avoir une variante du type `.fr-table--white-caramel` (ou autre, 
 je n'ai pas tous les noms des couleurs), pour les tableaux, pour que éviter d'avoir une couleur de fond trop chargée.

**Comment by jchourdeaux** [comment]
Hello @bzg , nous allons re étudier la demande ;) .
Bien cdt

**Comment by bzg** [comment]
Merci !

**Comment by lab9fr** [comment]
Bonjour Bastien

Cette variante est possible grâce au modificateur d'accentuation `fr-table--beige-gris-galet`

Bertrand, pour l'équipe DSFR

**Comment by bzg** [comment]
Super, merci !
