### ISSUE TITLE
Q: Implémentation Angular

### ISSUE THREAD

**Issue by comxd** [GouvernementFR/dsfr#315]
Bonjour,

D'après [cette page](https://gouvfr.atlassian.net/wiki/spaces/DB/pages/911245373/API+Javascript#Valeurs-possibles-%3A), il est prévu une implémentation vers Angular, disposez-vous déjà d'une roadmap publique ?

---

- [x] https://github.com/GouvernementFR/dsfr/pull/9

**Comment by jchourdeaux** [comment]
Bonjour @comxd, 
Il n'est pas prévu à l'heure actuelle une implémentation angular faite par l'équipe du dsfr. L'option mode sur le javascript est destiné à facilité l'implémentation mais cette dernière reste à la charge des utilisateurs et membres de la communauté .
Bien cordialement

**Comment by comxd** [comment]
Merci @jchourdeaux,

Entendu, du coup un maj de cette page pour préciser cela peut être nécessaire :
![image](https://user-images.githubusercontent.com/9022239/168052716-e4812891-0b0c-4d5d-96eb-5b3b756c0e24.png)
