### ISSUE TITLE
Plus de marges dans les groupes de buttons (v1.6.0)

### ISSUE THREAD

**Issue by demeyn** [GouvernementFR/dsfr#367]
Bonjour,

J'ai monté de version le DSFR sur un projet (de v1.5.1 à v1.6.0) et je m'aperçois que les groupes de buttons n'ont plus de marges entre eux. Je ne vois plus de propriété "margin" qui existait auparavant.

Le code disponible sur la documentation ne reflète pas non plus ce comportement (je ne crois pas que la documentation utilise la v1.6.0).

**Comment by jchourdeaux** [comment]
Bonjour @demeyn 
A priori il y a toujours des marges sur les groupes de boutons (https://main--ds-gouv.netlify.app/example/component/button/) . 
Avez-vous quelque chose à nous partager afin que l'on puisse reproduire le problème ? 
Bien cdt
