### ISSUE TITLE
Indicateur d'étapes - barre d'avancement non présente sur FF

### ISSUE THREAD

**Issue by t-veron** [GouvernementFR/dsfr#369]
Bonjour,

Sur Firefox (dernière version), la barre d'avancement ne s'affiche pas lorsque l'on affiche la dernière étape:

![image](https://user-images.githubusercontent.com/19189678/178012254-eaa6f13a-b657-4462-8bfd-3509e70e7b4a.png)

Sur la documentation officielle, le problème est également visible:

**Comment by comxd** [comment]
Bonjour @t-veron,

Je confirme, mais je valide la correction apportée sur la version 1.7.
