### ISSUE TITLE
Missing files from NPM package

### ISSUE THREAD

**Issue by comxd** [GouvernementFR/dsfr#388]
Bonjour,

Il semble que le dossier "/modules" ne soit pas publié, de fait la compilation ne fonctionne pas (ici avec Webpack) :

```
 Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
  SassError: Can't find stylesheet to import.
    ╷
  6 │ @use 'module/path';
    │ ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/@gouvfr/dsfr/src/main.scss 6:1                @import
    src/web/themes/custom/france_renov/src/scss/main.scss 3:9  root stylesheet
  SassError: SassError: Can't find stylesheet to import.
```

Fichier .scss du projet :

```
@import '~@gouvfr/dsfr/src/main';
...
```

**Comment by jchourdeaux** [comment]
Bonjour @comxd , 
merci beaucoup pour votre retour, un petit (gros) oubli dans le package.json de notre part.
Nous allons publier un correctif d'ici la fin de semaine. 
Bien cordialement

**Comment by comxd** [comment]
Fixed by v1.7.2 :heavy_check_mark: 

En revanche il nest nécessaire d'inclure l'intégralité du dossier `dsfr` dans les options Saas sans quoi la résolution du dossier "module" ne fonctionne pas, cela rallonge un peu le temps de compilation.

(webpack)
```
...
        {
          loader: "sass-loader",
          options: {
            implementation: require.resolve("sass"),
            sassOptions: {
              includePaths: [
                path.resolve(__dirname, 'node_modules/@gouvfr/dsfr/'),
              ],
            },
          },
        },
...
```
