### ISSUE TITLE
Rejeu du script

### ISSUE THREAD

**Issue by lilletech** [GouvernementFR/dsfr#39]
Bonjour,

Y a t'il possibilité de pouvoir faire un re-render ?

Les scripts ci-dessous initialisent les composants à la fin du chargement de la page.

    <script type="module" src="js/dsfr.module.min.js"></script>
    <script type="text/javascript" nomodule src="js/dsfr.nomodule.min.js"></script>

Par contre les composants ajoutés dynamiquement (après le chargement) ne sont, du coup, pas fonctionnel, il faudrait pouvoir re-initialiser.

Je crée actuellement un projet similaire à  https://github.com/betagouv/template-design-system-de-l-etat mais en version Angular (qui modifie le dom dynamiquement dans son système de routing) :
https://github.com/lilletech/angular-template-design-system-de-l-etat
 
Le dist est consultable -> https://lilletech.github.io/
Vous remarquerez le problème, notamment dans les tabs de la page colors

**Comment by lab9fr** [comment]
Bonjour,

Merci pour votre retour, 

Nous sommes actuellement en train de travailler sur le sujet avec une nouvelle version du JS qui supportera les framework dynamiques comme Angular, Vue et React

Le travail en cours est visible sur la PR #9

**Comment by lilletech** [comment]
Bonjour,

Parfait, merci pour cette information. Avez-vous une idée de date pour la release (beta/release candidate) ?

J'ai pull la branche de dev, mais impossible de compiler en local (erreur lors de 'yarn release' )... Probablement lié à mon environnement.

**Comment by lab9fr** [comment]
En l'occurence, il s'agit d'un petit problème de lint de notre côté dû à un des derniers merges.
Avec un `yarn build --clean`, vous aurez le build attendu :)

**Comment by lilletech** [comment]
Le problème que je rencontre n'est pas lié à lint.
A priori plus un problème avec le système de fichier (erreur lors de la création de dossier via les scripts du dossier tools).
=> mkdir

Environnement : windows 10, node v14.17.4, yarn 1.16.0

![image](https://user-images.githubusercontent.com/7681445/128609633-b344ed64-2cf0-4e98-9053-88274b112a1b.png)

**Comment by lilletech** [comment]
J'ai finalement opté pour une compilation via docker (image node:14). J'ai donc pu tester la fonctionnalité.

Mes premiers tests semblent plutôt positifs.

Merci :-)

**Comment by martinratinaud** [comment]
Bonjour

Avez vous un ETA sur le support de React ?
Nous utilisons cette lib sur un projet et du coup le breadcrumb ne fonctionne pas

Merci

**Comment by martinratinaud** [comment]
Alors du coup vu que j'en avais besoin, j'ai fait la chose suivante qui fonctionne mais qui n'est pas vraiment optimale.

- créé un fichier `src/modules/DesignSystem/tools/postinstall.js` qui va copier le fichier dans le répertoire `public`

```
const fs = require('fs/promises');
const path = require('path');

(async () => {
  const folder = path.join(process.cwd(), 'public', '@gouvfr', 'dsfr', 'dist', 'js');
  const dsfrFileSource = path.join(
    process.cwd(),
    'node_modules',
    '@gouvfr',
    'dsfr',
    'dist',
    'js',
    'dsfr.module.min.js'
  );
  const dsfrFileDest = path.join(folder, 'dsfr.module.min.js');
  await fs.mkdir(folder, { recursive: true });
  await fs.copyFile(dsfrFileSource, dsfrFileDest);
  console.info(`Copied ${dsfrFileSource} to ${dsfrFileDest}`);
})();

```

- ajouté un script postinstall

```
"scripts": {
    "postinstall": "node src/modules/DesignSystem/tools/postinstall.js",
  },
```

- Inclus ce script dans `_app.tsx`

```
import Script from 'next/script';
<Script
        {/* See https://github.com/GouvernementFR/dsfr/issues/39 */}
          src={`${process.env.NEXT_PUBLIC_BASE_PATH}/@gouvfr/dsfr/dist/js/dsfr.module.min.js`}
        />
```

Mais je suis toujours friand de votre ETA sur cette feature :-)

Merci

**Comment by lilletech** [comment]
[_dist.zip](https://github.com/GouvernementFR/dsfr/files/7038467/_dist.zip)

(En attendant, si ca peut aider , voici le résultat d'une compilation toute fraiche du matin de la branche dev). Attention, l'organisation de l'arborescence dans le dist a changé. (chemin vers fichier js, css).

Pour l'instant, le seul problème que j'ai détecté de mon côté c'est dans la page composant ( je n'ai pas l'icône). 
![image](https://user-images.githubusercontent.com/7681445/130601568-54086025-dc4f-47e6-bbb5-b717392c1c9b.png)

**Comment by lab9fr** [comment]
La version 1.2.0 permet maintenant l'utilisation du JS de manière réactive.
