### ISSUE TITLE
Navigation au clavier impossible au sein d'un onglet avec les flèches gauche et droite

### ISSUE THREAD

**Issue by bellangerq** [GouvernementFR/dsfr#392]
Bonjour 👋🏼 

La navigation au clavier **avec les flèches directionnelles gauche et droite ne semble pas fonctionner sur les composants englobés au sein d'un système d'onglet**. Quelques exemples :
- Input / Textarea : avec les flèches gauche et droite, on ne peut pas se déplacer au sein de la saisie.
- Boutons radio : avec les flèches gauche et droite, on ne peut pas changer la valeur sélectionner (seulement les flèches haut et bas).

En effet, un event `keydown` sur l'élément avec la classe `fr-tabs` bloque. Si on le toggle, il est de nouveau possible d'utiliser les flèches à l'intérieur de l'onglet.

<img width="557" alt="image" src="https://user-images.githubusercontent.com/13785417/184363720-4af50fa6-90cb-471e-a431-70be6fba35b3.png">

Voici un exemple de reproduction minimale :
- Démo live : https://spectacular-ganache-cb3c18.netlify.app/
- Repository : https://github.com/bellangerq/dsfr-navigation-arrows-reproduction

Merci et bonne journée 😃

**Comment by jchourdeaux** [comment]
Bonjour @bellangerq 
(désolé pour la réponse tardive)
Merci pour votre retour, nous avons en effet également constaté ce problème qui a été ajouté à notre backlog. 
Nous vous tenons informé quand à sa résolution.
BIen cordialement

**Comment by bellangerq** [comment]
Je me permets de compléter : je viens de constater que le problème est aussi présent avec les touches `HOME` et `END`, toujours sur les champs dans des onglets (aussi testable sur le lien de repro initialement fourni).

**Comment by lab9fr** [comment]
Bonjour Quentin, 

La version 1.10 incorpore le correctif qui permet de séparer la navigation clavier dans les input / textarea de la navigation des onglets.
Ce bug nous aura pris beaucoup de temps à être fixé, c'est maintenant le cas ! 

Merci de nous l'avoir rapporté
Bertrand, pour l'équipe DSFR
