### ISSUE TITLE
Navigation au clavier dans un menu n'est pas conforme aux recommandations d’ARIA

### ISSUE THREAD

**Issue by tchak** [GouvernementFR/dsfr#395]
Nous venons de remplacer certains menus sur demarches-simplifiees.fr par l'implémentation de `dsfr` et on se rend compte que la navigation au clavier dans les menus ne fonctionne plus. J'ai cherché rapidement dans le code js et effectivement je ne trouve pas la gestion du clavier pour les menus.

Notre propre implémentation avant `dsfr` était basée sur cet exemple https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-actions.html

**Comment by jchourdeaux** [comment]
Bonjour @tchak .
Concernant les menus de navigation nous nous basé sur le pattern disclosure , qui est légèrement différent
https://www.w3.org/WAI/ARIA/apg/example-index/disclosure/disclosure-navigation 

Vous avez un exemple précis afin que nous rendre compte des impacts sur votre code ?

Bien cordialement

**Comment by tchak** [comment]
Je comprends. Je trouve que c'est dommage de perdre la navigation avec les flèches dans les menus. Pour référence, voici notre implémentation actuelle : https://github.com/betagouv/demarches-simplifiees.fr/blob/d4ab97f2707c9f910e3e9505113500d0486c7a19/app/javascript/controllers/menu_button_controller.ts

**Comment by tchak** [comment]
Notre implémentation fonctionne en deux modes `menu` et `popover`. Il y a une implémentation de `popover` dans DSFR ?

**Comment by tchak** [comment]
Je viens de voir que dans l'exemple "Disclosure Navigation" la navigation avec les flèches est censée être implémentée aussi
