### ISSUE TITLE
Utilisation d'ancres au sein d'onglets

### ISSUE THREAD

**Issue by bellangerq** [GouvernementFR/dsfr#404]
L'utilisation d'ancres (`<a href="#section">Lien vers la section</a>`) ne fonctionne pas au sein d'un onglet.

Une fois le lien cliqué, on est bien redirigé vers la section correspondante. En revanche, le système d'onglet est visuellement cassé (cf screenshot joint).

Ce comportement est identique si on accède directement à la page avec l'ancre dans l'URL ([https://example.com#foobar](https://hilarious-horse-27381c.netlify.app/#lorem)).

<img width="371" alt="image" src="https://user-images.githubusercontent.com/13785417/190519035-fcdd7a14-fbef-449e-a3e6-5406aef6620e.png">

Voici un exemple de reproduction minimale :

- Démo live : https://hilarious-horse-27381c.netlify.app/
- Repository : https://github.com/bellangerq/dsfr-tabs-anchor-reproduction

Merci, bonne journée 😃

**Comment by lab9fr** [comment]
Bonjour Quentin, 

Merci d'avoir trouvé ce bug bien caché et du temps consacré à le renseigner. 🙏 
Je rentre ce problème dans nos points à traiter.

Merci et bonne soirée

**Comment by lab9fr** [comment]
Livré dans la 1.10
