### ISSUE TITLE
Composant Paramètres d'affichage responsive

### ISSUE THREAD

**Issue by misterdoak** [GouvernementFR/dsfr#409]
Le composant  **Paramètres d'affichage** ne semble plus fonctionner quand il est intégré au burger menu :

- la valeur de l'attribut **aria-controls** passe à **fr-theme-modal_copy**
- la modale a toujours pour id **fr-theme-modal**

Au clic sur le bouton, la modale n’apparaît pas.

DSFR **v1.7.2**

**Comment by lab9fr** [comment]
Bonjour @misterdoak,
Merci pour votre rapport de bug
Pouvez-vous nous partager votre implémentation pour y voir plus clair ?
Merci
Bertrand

**Comment by misterdoak** [comment]
Bonjour,

J'ai suivis la documentation, du coup mon intégration en comme ci-dessous :
<div class="fr-header__tools-links">
<ul class="fr-btns-group">
<li>
<button class="fr-btn fr-fi-theme-fill fr-btn--icon-left" aria-controls="fr-theme-modal" data-fr-opened="false">{{ 'params-view' |trans }}</button>
</li>
</ul>
</div>

Le DSFR est installé comme ci-dessous :+1:

**Comment by misterdoak** [comment]
Bonjour,

Constatez vous le même problème de votre côté?

Merci

**Comment by yaaax** [comment]
J'ai le même problème, reproduit ici : [https://parcoursup-design.netlify.app/](https://parcoursup-design.netlify.app/)

**Comment by lab9fr** [comment]
Bonjour, 

Merci pour vos retours.

Nous avons identifié la cause de cette problématique, elle est en cours de traitement.

Merci

**Comment by lab9fr** [comment]
Fixed #454
