### ISSUE TITLE
Composant input date - affichage du calendrier

### ISSUE THREAD

**Issue by AzuriDigital** [GouvernementFR/dsfr#411]
Bonjour,

L'affichage du calendrier lors du clique sur l'icône calendar ne fonctionne pas correctement. 
Il faut cliquer légèrement à gauche de l'icône pour que le calendrier natif du navigateur s'affiche.

  
![image](https://user-images.githubusercontent.com/598450/192002338-939cc143-d108-490c-980b-888ee98c3d53.png)

Bonne soirée 😉

**Comment by lab9fr** [comment]
bonjour @AzuriDigital,

Merci pour votre retour.

C'est un problème que nous avons repéré et qui est en attente de traitement par notre équipe ;)

Merci et bonne journée

**Comment by brmzkw** [comment]
Je confirme. Sur firefox, il y a deux icônes : la première ouvre le calendrier, la seconde donne le focus sur l'élément.

**Comment by florimondmanca** [comment]
Sous Firefox, est-ce qu'un correctif pourrait consister à ne pas afficher l'icône calendrier DSFR (le `::before`) et ne laisser que le calendrier natif ?

**Comment by lab9fr** [comment]
Corrigé dans la 1.10
