### ISSUE TITLE
Import de la librairie dans un nœud Shadowdom

### ISSUE THREAD

**Issue by azouali** [GouvernementFR/dsfr#418]
Bonjour,

Quand on importe la librairie dans un composant shadowdom, le `:root` et toutes les propriétés définis dedans sont ignorés, les styles ne sont donc pas correctement appliqués.

L'import de la librairie au niveau global n'est pas une option pour moi, car cela va causer des conflits avec d'autres règles globales.

Serait-il possible de détacher la définition des propriétés dans un fichier CSS séparé (dsfr.main.css::root {....}), puis l'importer dans le `dsfr.main.css` ? Cela donnerait la possibilité d'importer les propriétés sans les surcharges qui vont avec.

Ou si vous avez d'autres propositions je suis preneur.
Je vous remercie d'avance.

**Comment by lab9fr** [comment]
Bonjour @azouali,

Merci de vos retours.

Ce sont des réflexions sur lesquelles nous nous penchons actuellement, mais qui demandent un remaniement profond de la librairie.
Nous vous tiendrons au courant de nos avancées sur le sujet dans les prochains mois.

Merci
Bertrand

**Comment by lab9fr** [comment]
Le sujet est inclu dans les réflexions pour la v2
