### ISSUE TITLE
Suppression des informations DSFR dans la console 

### ISSUE THREAD

**Issue by AzuriDigital** [GouvernementFR/dsfr#421]
Bonjour,

Avec l'option verbose à false, la console remonte encore certaines informations. Est-il possible de les supprimer (dsfr : version, mode set etc) 

Bonne journée

**Comment by lab9fr** [comment]
Bonjour, 
Ce n'est effectivement pas documenté, mais c'est possible avec l'action suivante : 
`dsfr.inspector.level = 10`
Bonne jpurnée

**Comment by azurams** [comment]
Bonjour, 
pouvez vous préciser à quel endroit il est possible de paramétrer `dsfr.inspector.level = 10` ?
