### ISSUE TITLE
Présence de commentaires dans la version minifiée du DSFR

### ISSUE THREAD

**Issue by freesteph** [GouvernementFR/dsfr#435]
le [DSFR minifié](https://beta.gouv.fr/assets/gouvfr/dsfr.min.css) inclut une multitude de commentaires `/* media lg */`, sûrement tirés de https://github.com/gouvernementfr/dsfr/blob/main/module/shame/media-query/mixin/_order.scss#L8. Est-ce normal ?

**Comment by lab9fr** [comment]
Bonjour @freesteph ,

C'est un problème que nous avons identifié, merci pour le rapport de bug.
Nous cherchons une solution.

Merci et bonne soirée
Bertrand

**Comment by lab9fr** [comment]
Ce sujet demande un refonte profonde qui sera un des objets de la v2
