### ISSUE TITLE
Dark mode broken

### ISSUE THREAD

**Issue by laurentguenver-a** [GouvernementFR/dsfr#440]
Bonjour,

Le dark mode ne fonctionne plus depuis le passage à la version 1.8.0.
C'est à dire que lorsque je suis en mode Dark, l'affichage est identique au mode light.

Cela fonctionnait très bien en 1.7.2.

Merci.

**Comment by lab9fr** [comment]
Merci pour ce rapport de bug rapide, le sujet est traité et va être livré.
