### ISSUE TITLE
Shadow nodes with DSFR components not registered by scripts.

### ISSUE THREAD

**Issue by azouali** [GouvernementFR/dsfr#445]
Bonjour,

L'import des JS (module & nomodule) permet le comportement dynamique des différents composants DSFR (modal, accordéon, lien de téléchargement ...). Ce ne semble cependant pas fonctionner sur des nœuds ShadowDom, les modales ne se déclenchent pas par exemple.

Après quelques recherches, je me rends compte que c'est dû au fait que les nœuds ShadowDom ne sont pas détectés/ajoutés lors de la mutation du DOM, ils ne sont donc pas enregistré par les scripts DSFR.

Je ne suis pas sûr que c'est une issue liée au DSFR elle même, mais je demande quand même si des solutions de contournement sont prévues par la librairie.

En vous remerciant d'avance.

**Comment by lab9fr** [comment]
duplicate #418

**Comment by azouali** [comment]
> 

Mon message porte sur une problématique différente de la #418, cette dernière traite des propriétés déclarés dans le :root qui sont ignorées dans le shadowDom. Là il est question des traitements JS.
