### ISSUE TITLE
Class "fr-logo--lg" ne fonctionne pas dans le header

### ISSUE THREAD

**Issue by tydoo** [GouvernementFR/dsfr#450]
Bonjour, 

Voulant copier le header de "https://www.service-public.fr/", je viens de m'apercevoir que la classe "fr-logo--lg" ne fonctionne pas quand on la rajoute dans le header.

```html
<div class="fr-header__logo">
    <p class="fr-logo fr-logo--lg">
        Ministère<br>de l'Intérieur<br>et des outre-mer
    </p>
</div>
```

Le texte : 
![image](https://user-images.githubusercontent.com/50534204/199961431-c80b1cf1-f877-448d-9097-0e47f52cc75d.png)

La Mariane (before): 
![image](https://user-images.githubusercontent.com/50534204/199961919-86f63190-9229-425f-8331-7c61a3317c8d.png)

La devise (after): 
![image](https://user-images.githubusercontent.com/50534204/199961963-e2fdbd22-872b-4803-9f63-9d5e1614e65f.png)

Ce serrait bien de pouvoir l'avoir nativement dans la DSFR, et ne pas devoir faire un code spécifique comme ils ont du faire pour service-public.fr.

Merci

**Comment by lab9fr** [comment]
Bonjour @tydoo , 

Les autres tailles pour le logo sont désactivées dans le header parce qu'elles ne sont pas autorisées.
La seule taille permise est la taille native dans le composant.
Il faut donc éviter de faire un code spécifique pour la modifier.

Merci
Bertrand
