### ISSUE TITLE
Icone a droite sur un bouton DOWN

### ISSUE THREAD

**Issue by tydoo** [GouvernementFR/dsfr#459]
v1.8.2
![image](https://user-images.githubusercontent.com/50534204/201075438-32484dcd-aadf-49fc-80da-f533e1e48f3c.png)

**Comment by lab9fr** [comment]
Bonjour @tydoo, 

Merci pour ce rapport de bug, nos équipes sont en train de le traiter.

Bonne soirée
Bertrand
