### ISSUE TITLE
Problème de style sur les inputs de type "submit" désactivés

### ISSUE THREAD

**Issue by ClemDee** [GouvernementFR/dsfr#46]
Version du dsfr utilisée: 1.1.0

## Problème constaté

Les inputs de type "submit" désactivés ne sont pas grisés, et le curseur de la souris reste en mode "pointeur".
```html
<!-- Le style n'est pas désactivé -->
<input type="submit" class="fr-btn" value="Envoyer" disabled />
```

## Comportement attendu

Les inputs de type "submit" devraient avoir le même style que les boutons `<button>` lorsqu'ils sont désactivés.
```html
<!-- Devraient être semblables à -->
<button class="fr-btn" disabled>Envoyer"</button>
```

**Comment by lab9fr** [comment]
Bonjour ClemDee, 

Merci pour votre retour détaillé et précis :) 
Nous allons étudier le problème et le corriger prochainement.
