### ISSUE TITLE
Composant display ne fonctionne pas au changement de page avec @hotwired/turbo

### ISSUE THREAD

**Issue by tydoo** [GouvernementFR/dsfr#462]
J'utilise la librairie @hotwired/turbo (anciennement Turbolinks) pour pouvoir charger les pages de façon dynamique en ajax automatiquement.

Cependant, il semble que le composant **display** n'est pas compatible.

Au premier chargement du site, le composant fonctionne et affiche bien la modal.

Mais **au changement de page**, le clic sur le bouton ne fonctionne pas, et aucun modal ne s'affiche.

Cependant, on vois bien la scroolbar qui est caché au clic (donc le bouton réponds bien).

**Ps** : Le javascript fonctionne bien avec @hotwired/turbo, car je n'ai aucun soucis avec le composant accordion. Il fonctionne parfaitement au changement de page.

https://www.npmjs.com/package/@hotwired/turbo

**Comment by lab9fr** [comment]
Bonjour @tydoo ,

Serait-il possible de nous mettre à disposition le code permettant de reproduire le problème ?

Merci
Bertrand

**Comment by lab9fr** [comment]
Bonjour, 

Il s'agit d'un problème de compatibilité avec une librairie tierce. Si vous trouvez un correctif spécifique, nous pourrons l'intégrer au sein du DSFR. En attendant, nos équipe n'aurons pas la disponibilité pour traiter ce type de problèmes

Bertrand, pour l'équipe DSFR
