### ISSUE TITLE
Release 1.8.4 - La compilation des css dans dist/dsfr ne sont pas à jour

### ISSUE THREAD

**Issue by laurent974** [GouvernementFR/dsfr#470]
Je prends l'exemple de la transcription des medias:

Ce qu'on a actuellement : 
```
.fr-content-media__transcription .fr-link {
  font-size: 0.875rem;
  line-height: 1.5rem;
  min-height: 2rem;
  padding: 0.25rem 0.75rem;
  overflow: initial;
  max-width: 100%;
  max-height: none;

  --underline-img: none;
  --hover-tint: var(--hover);
  background-color: transparent;

  --hover: inherit;
  --active: inherit;
  color: var(--text-action-high-blue-france);
}
```

alors qu'on devrait avoir :
```
.fr-content-media__transcription .fr-btn {
  ...
}
```

**Comment by lab9fr** [comment]
Bonjour @laurent974 ,

Merci pour ce rapport.

Le code du fr-link correspond à une assez ancienne version que l'on avait conservé en version dépréciée, mais qui ne devrait plus être présente dans le code. Nous ferons la correction en le supprimant.
Le bouton de transcription correspond à une version minimale qui permettait de laisser à chacun la possibilité de mettre en place la fonctionnalité de la transcription tant que le composant n'était pas produit.
Le composant de transcription est maintenant disponible, il est préférable de faire la transition vers son implémentation. Le bouton de transcription est maintenant obsolète.

Merci 
Bertrand
