### ISSUE TITLE
Le thème sombre ne fonctionne plus depuis la version 1.7.2 et malgré la correction 1.8.1.

### ISSUE THREAD

**Issue by lhadjadj** [GouvernementFR/dsfr#472]
Etablissement : FranceAgriMer
Architecture : Angular 14/springboot 2.3.12

Nous utilisons le SDE depuis la version 1.4.1. Depuis la version 1.8.1 nous constatons que le mode sombre ne fonctionne plus, malgré une correction intégrée (#440, #442).

Nous avons mis à jour la version en 1.8.2 et en 1.8.4 mais nous avons toujours le même problème. 
Nous n'avons pas d'erreur, les logos changent bien en fonction du choix du thème. La balise thème et schème prennent la bonne valeur par contre nous restons sur la même couleur, celle du thème clair.

**Comment by lab9fr** [comment]
Bonjour @lhadjadj ,

Pourriez-vous nous donner accès à vos pages pour que nous puissions déterminer le problème ?

Merci et bonne soirée
Bertrand

**Comment by lhadjadj** [comment]
Oui demain, et comment ?Envoyé de mon iPadLe 16 nov. 2022 à 19:49, lab9 ***@***.***> a écrit :﻿
Bonjour @lhadjadj ,
Pourriez-vous nous donner accès à vos pages pour que nous puissions déterminer le problème ?
Merci et bonne soirée
Bertrand

**Comment by lab9fr** [comment]
Bonjour 

Vous pouvez envoyer un mail à lab9@gmail.com

**Comment by lhadjadj** [comment]
Bonjour, j'ai effectué une revue de code complète jeudi dernier (17/12/2022) dans le cadre d'un audit de notre archétype et j'ai identifié plusieurs différences entre notre code (qui permettait en version 1.5.1 de faire tourner le mode sombre) et l'implémentation 1.8.4. 
En portant ces modifications au niveau de notre page index.html (sous angular+angular.json), nous constatons que tout fonctionne correctement en version 1.8.4. 

Je pourrais vous indiquer les modifications si vous le souhaitez, car développeur a été bloqué pendant plusieurs semaines. Et je n'ai pas trouvé dans la doc en ligne les éléments. C'est en lisant la doc du paquet npm et en comparant le code que j'ai pu constater un écart.
