### ISSUE TITLE
Question / Chemin alternatif pour les fonts

### ISSUE THREAD

**Issue by sylvainlg** [GouvernementFR/dsfr#485]
Bonjour,

J'aimerais héberger les différents fichiers des polices sur un CDN.
Comment spécifier un autre chemin que `/fonts/Marianne-Regular_Italic.woff` ?

Merci d'avance

**Comment by lab9fr** [comment]
Bonjour Sylvain, 

Ce n'est actuellement pas réellement possible, c'est une question qui est en cours et qui va demander un certain délai pour être solutionné.
Nous vous tiendrons au courant quand la solution approche.

Bonne journée
Bertrand

**Comment by lab9fr** [comment]
Sujet à traiter en v2
