### ISSUE TITLE
Conflit de fonctionnement entre les modales et le style `scroll-behaviour: smooth`

### ISSUE THREAD

**Issue by thibault** [GouvernementFR/dsfr#515]
Je rencontre un problème de comportement à la fermeture d'une modale lorsque on a défini un attribut `scroll-behaviour: smooth` sur la balise html.

## Opérations réalisées

 - je navigue sur n'importe quel site utilisant le dsfr
 - je configure l'attribut de style `scroll-behaviour` à `smooth` sur la balise html
 - je scroll sur une page
 - j'ouvre une fenêtre modale, puis je la referme

## Comportement attendu

La modale se ferme. Le site en arrière plan redevient visible et "focusable" mais n'a pas bougé.

## Comportement constaté

Le navigateur remonte en haut de la page et re-scroll à l'emplacement qui était le mien au moment de l'ouverture de la modale.

## Vidéo

Voici une capture vidéo pour mieux visualiser le problème.

Sur cet exemple, je clique sur une ancre depuis un site ayant configuré le `scroll-behaviour` à `smooth`. Puis j'ouvre puis referme une modale. On constate le scroll intempestif dès que je referme la modale.

[Capture vidéo du 2023-01-17 10-58-50.webm](https://user-images.githubusercontent.com/11499/212868008-4562f863-27d7-498a-ad68-ec663ee9f011.webm)

## Contournement

Pour l'instant, je contourne honteusement le problème grâce au code suivant :

```js
    <script>
      window.addEventListener('load', function() {
        let modals = document.querySelectorAll('.fr-modal');
        let root = document.documentElement;

        modals.forEach(function(modal) {
          modal.addEventListener('dsfr.disclose', function() {
            root.style.scrollBehavior = 'auto';
          });
          modal.addEventListener('dsfr.conceal', function() {
            setTimeout(function() {
              root.style.removeProperty('scroll-behavior');
            }, 300);
          });
        });
      });
    </script>
```

## Détails

Problème constaté avec Chromium Version 109.0.5414.74 (Build officiel) snap (64 bits). Le problème ne se présente pas avec Firefox.

 DSFR v1.8.5

**Comment by lab9fr** [comment]
Bonjour Thibault,

Merci pour ce rapport de bug super détaillé.
Nous allons traiter le sujet prochainement et vous tiendrons au courant des évolutions.

Bonne journée
Bertrand

**Comment by lab9fr** [comment]
Correctif livré dans la 1.10
