### ISSUE TITLE
Coquille dans la doc

### ISSUE THREAD

**Issue by rebeccadumazert** [GouvernementFR/dsfr#516]
Bonjour,

Ma collègue a remarqué une coquille dans la doc du DSFR qui fait buguer prettier.

C'est sur la page suivante : 

https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte

Un h3 est en double dans la balise.

Je vous joins un screenshot 

<img width="844" alt="Capture d’écran 2023-01-18 à 15 37 21" src="https://user-images.githubusercontent.com/44778533/213199856-aa311f86-4b69-4d7b-9f4a-75df392c5a2d.png">

**Comment by lab9fr** [comment]
Bonjour Rebecca,

Merci pour ce rapport de bug
Nous allons traiter ça prochainement
Bonne journée
Bertrand
