### ISSUE TITLE
La navigation clavier au sein d'un champ de texte ne fonctionne pas dans un onglet

### ISSUE THREAD

**Issue by mlbiche** [GouvernementFR/dsfr#517]
Si un champ de texte est placé dans un onglet (`tab`), l'utilisation des flèches _Droite_ et _Gauche_ pour naviguer au sein du texte saisi ne fonctionne pas.

Il est interrompu par ce morceau de code :

https://github.com/GouvernementFR/dsfr/blob/8f97ecaea61f49e9d450f4132dbb507fa337c8e6/src/component/tab/script/tab/tabs-group.js#L20

Ne connaissant pas le contexte qui a mené à la rédaction de ce code, je n'ai pas vraiment de recommandation à faire. Cependant, ce comportement est assez inattendu et surtout très compliqué à debugger. Il m'a fallu un petit moment pour trouver le coupable (mon code, le DSFR, le navigateur ?) qui empêchait cette navigation dans un champ dans une modale ouverte depuis un onglet.

**Comment by lab9fr** [comment]
Bonjour @mlbiche,
Merci pour ce rapport de bug.
Ce problème a été identifié en #392 et nous avons mis en place un correctif qui sortira dans la version 1.10
Bonne journée
Bertrand
