### ISSUE TITLE
Version de Penpot

### ISSUE THREAD

**Issue by vinyll** [GouvernementFR/dsfr#527]
Penpot est un logiciel qui, comme Figma ou Sketch, permet de créer des interfaces et simuler des actions.
La différence majeure est que Penpot est totalement open source.
Il serait intéressant que le DSFR ne dépende pas d'outils fermés et propriétaires, et ne soit pas incitatif à d'autres utilisateurs et startups à s'orienter vers ces outils quand des solutions libres et solides existent.

À cette fin, je propose que Penpot soit considéré comme outil principal pour l'édition et l'utilisation du DSFR.
Y-a-t'il des personnes au sain de l'équipe qui est déjà passé à Penpot ?

**Comment by lab9fr** [comment]
Bonjour Vincent,

J'ai transmis le message à nos équipes UI, merci pour la suggestion
Cet espace est plutôt consacré à la partie développement du DSFR, pour les demandes d'évolutions, il est préférable de passer par https://systeme-de-design.featureupvote.com/ ou https://gouvfr.atlassian.net/servicedesk/customer/portal/1/group/1/create/4
Je vais clôturer ce sujet.

Merci et bonne journée
Bertrand
