### ISSUE TITLE
Les icônes dans le menu principal sont-elles officiellement autorisées ?

### ISSUE THREAD

**Issue by cyril-lamotte** [GouvernementFR/dsfr#558]
Bonjour,

J'intègre actuellement un nouveau site DSFR, je remarque que quelques sites qui appliquent le DSFR ont une icône "Home" à la place de "Accueil" dans le menu principal.
Dans la documentation du composant "Navigation principal", il est indiqué clairement "**Ce composant n’est pas personnalisable**".
En conséquence, mettre une icône fait-il partie de la personnalisation, ou est-ce autorisé ?

**Comment by lab9fr** [comment]
Bonjour Cyril, 
Il s'agit plutôt d'une question d'UX-UI alors que nous traitons ici les problèmes techniques.
Je vous invite à poser votre question sur slack dans le canal #aide_ux_ui ou sur le centre de support : https://gouvfr.atlassian.net/servicedesk/customer/portal/1/group/1/create/4
Cordialement
Bertrand

**Comment by cyril-lamotte** [comment]
C'est UX UI en effet, je vais faire une question merci !
