### ISSUE TITLE
Numéros de version incohérents dans la documentation

### ISSUE THREAD

**Issue by sblondon** [GouvernementFR/dsfr#562]
La [documentation](https://www.systeme-de-design.gouv.fr/comment-utiliser-le-dsfr/developpeurs/prise-en-main-du-dsfr/) indique que la dernière version est la 1.8.5 et qu'elle est téléchargeable. Mais l'archive téléchargeable est la 1.7.2.

Sur [npm](https://www.npmjs.com/package/@gouvfr/dsfr), la dernière version est la 1.9.0.

Si vous ne publiez plus d'archive, il faudrait simplement modifier le texte. Je suppose que la documentation est produite sur Confluence/Bitbucket car je ne l'ai pas vu dans le dépôt dsfr ou dans un autre dépôt de GouvernementFR.

**Comment by lab9fr** [comment]
Bonjour @sblondon,

Merci de nous avoir rapporté ce problème, nous allons le traiter rapidement, il s'agit de résidus d'anciennes versions.
La nouvelle version est accessible ici : 
https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/developpeurs/prise-en-main/
https://www.systeme-de-design.gouv.fr/a-propos/versions/version-courante 

Cordialement
Bertrand pour l'équipe DSFR

**Comment by sblondon** [comment]
@lab9fr merci pour la réactivité. :)

Je suggère de supprimer le terme « ci-dessous » de la section Fichiers statiques dans la phrase « Il est possible de télécharger l'ensemble du DSFR au format zip ci-dessous. » puisque les fichiers sont stockés sur GitHub.
