### ISSUE TITLE
Problème de contraste sur les inputs

### ISSUE THREAD

**Issue by pierre-isb** [GouvernementFR/dsfr#578]
Hello ! 
J'espère que vous allez bien.

Suite à un audit d'accessibilité de la DINUM dans le cadre d'un projet pour la Sécurité Routière, on nous a remonté un problème de contraste sur les inputs, notamment quand ils sont sur fond gris (cf. pages de connexion et d'inscription). 
Sans la couleur de fond on ne distingue que la ligne du bas, ce qui rend l'input difficilement reconnaissable.

L'auditeur (M. Sélim Meziti) nous a conseillé de pallier à ce manque de visibilité en affichant la bordure complète de l'input en mode contraste élevé (comme en HTML natif), d'où la PR corrective que je viens de créer : cf. #577 

À disposition si vous souhaitez en discuter ou si vous avez besoin de plus d'informations !
Pierre I.

**Comment by pierre-isb** [comment]
Pour imager le comportement actuel vs. le comportement attendu/corrigé en mode contraste élevé :
![Capture d’écran 2023-04-14 à 15 46 13](https://user-images.githubusercontent.com/55983581/232061145-a5f42f93-a8da-44b7-9dd6-20d03364e73a.png)
![Capture d’écran 2023-04-14 à 15 46 24](https://user-images.githubusercontent.com/55983581/232061149-a0bae778-5bd6-497f-a7f2-1029a98d1bbe.png)

**Comment by lab9fr** [comment]
Ce sujet demande une refonte en profondeur et fait partie des chantiers de la v2
