### ISSUE TITLE
Fichier généré invalide

### ISSUE THREAD

**Issue by l-vincent-l** [GouvernementFR/dsfr#593]
### Décrire le bug
Le fichier CSS distribué ne respecte pas les standards CSS3.

### Les étapes pour reproduire le bug

Si on passe le fichier https://cdn.jsdelivr.net/npm/@gouvfr/dsfr@1.9.2/dist/dsfr.css dans https://jigsaw.w3.org/css-validator/ on obtient un certain nombre d’erreurs.

Le rapport est visible [ici](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdn.jsdelivr.net%2Fnpm%2F%40gouvfr%2Fdsfr%401.9.2%2Fdist%2Fdsfr.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=fr) 

On note une première erreur simple à rectifier `no-wrap` -> `nowrap`
~~Des erreurs autour des valeurs de `aspect-ratio` non conforme, ce que je n’explique pas.~~ C’est en fait mal géré par le validateur
Des paddings négatifs ce qui est contraire à la spécification CSS.
~~Et finalement des erreurs de syntaxe.~~ C’est en fait mal géré par le validateur

### Comportement attendu

On ne voudrait pas qu’il y ait d’erreurs.

### Configuration et système utilisé
- **Version du DSFR : ** 1.9.1
- **Appareil (mobile, tablette, desktop) : ** validateur CSS

**Comment by l-vincent-l** [comment]
Pour les ratios, je pense que l’erreur vient du validateur voir l’issue https://github.com/validator/validator/issues/1406

**Comment by l-vincent-l** [comment]
Je pense que les erreurs de syntaxe sont causé par l’utilisation de `selector` qui est encore en expérimental, et pas implémenté par le validateur.

En vraies erreurs il reste donc les padding négatifs, et en tant que développeur back, je ne me sens pas du tout de les corriger sans tout casser :grinning:

**Comment by lab9fr** [comment]
Merci pour ce rapport de bug

Je créé un ticket concernant les padding négatifs. Sans que ce soit dommageable, ça prend du poids inutilement.

Bertrand pour l'équipe DSFR

**Comment by lab9fr** [comment]
corrigé en v1.10
