### ISSUE TITLE
La classe CSS fr-header__body n'existe pas

### ISSUE THREAD

**Issue by edugouvfr** [GouvernementFR/dsfr#603]
### Décrire le bug
La classe `CSS fr-header__body` est utilisée dans le template HTML du header mais n'existe pas du côté feuille de style CSS

### Les étapes pour reproduire le bug
1. Examiner le balisage du header
2. Constater l'usage qui est fait de la classe `fr-header__body`
3. Rechercher cette classe dans la feuille de style agrégée
4. Constater qu'elle n'existe pas

### Comportement attendu
Le template HTML du header ne devrait pas référencer une classe CSS inexistante

### Configuration et système utilisé
- **Version du DSFR : **
- Constaté sous DSFR 1.3.0, 1.8.5, 1.9.2

**Comment by edugouvfr** [comment]
complément : même chose pour la classe `fr-header__service-tagline`

**Comment by lab9fr** [comment]
Bonjour,

Ces classes sont en place en prévision de l'évolution du header et pour faciliter les mises à jour.
Certaines fonctionnalités prévues de longue date mais encore non confirmées et implémentées nécessitent ces classes.

Merci pour ce rapport
Bertrand pour l'équipe DSFR

**Comment by edugouvfr** [comment]
Merci pour votre retour. Nous maintenons donc ces classes en attendant. Vous pouvez donc clôturer le ticket.
