### ISSUE TITLE
Alléger les pages de la documentation

### ISSUE THREAD

**Issue by bricedurand** [GouvernementFR/dsfr#616]
Aujourd'hui, les pages de la documentation du DSFR sont très lourdes.

Par exemple, le simple fait de charger la [page sur les éléments d'interface](https://www.systeme-de-design.gouv.fr/elements-d-interface) représente 15Mo. C'est principalement les requêtes au fichier "payload.js" : 

![2023-06-14 Page composants - Système de Design de l'État](https://github.com/GouvernementFR/dsfr/assets/1522772/42ed1eff-72fd-4e65-b96d-893b6a6d3ab8)

<img width="772" alt="2023-06-14 Requête page de documentation DSF" src="https://github.com/GouvernementFR/dsfr/assets/1522772/0ee8a505-bfeb-4112-a19a-24b6589b2c65">

\
\
Si je fais défiler la page jusqu'en bas, pour voir le composant tag dont j'avais besoin, on arrive pas loin des 100Mo : 

![2023-06-14 Page composants défilée en bas - Système de Design de l'État](https://github.com/GouvernementFR/dsfr/assets/1522772/77020d9b-cc3a-479a-b98e-a5a6d0a5cf68)

<img width="772" alt="2023-06-14 Poids de la page éléments d'interface scrollée en bas" src="https://github.com/GouvernementFR/dsfr/assets/1522772/9f33cb14-4c1a-4714-a76c-85cf40439a6a">

\
\
C'est vraiment pénalisant pour moi qui utilise très souvent le partage de connexion 4G. De plus l'affichage de la page est légèrement saccadé.

Pour éviter ça, je tape directement dans un moteur de recherche "design système de l'État - nom_du_composant" pour accéder à la bonne page. Ensuite je supprime le menu de gauche via les outils de développement du navigateur (clic droit > Inspecter), ce qui permet d'éviter certaines requêtes au défilement de la page. Mais vous conviendrez que c'est pénible...

Si vous résolvez ça, mon forfait 4G sera ravi, et moi aussi :-)

**Comment by lab9fr** [comment]
Bonjour Brice, 

Merci pour ce rapport de bug.
C'est un sujet dont nous avons pleinement conscience au sein de l'équipe.
Nous sommes en train d'étudier des solutions, une résolution viendra prochainement.

Cordialement
Bertrand, pour l'équipe DSFR
