### ISSUE TITLE
Retirer les commentaires des fichiers dans `dist/`

### ISSUE THREAD

**Issue by davidbgk** [GouvernementFR/dsfr#617]
### Décrire le bug

Les fichiers dans le dossier `dist/` des releases contiennent les commentaires `/*! media sm/md/lg/xl */` (environ 400 fois pour `dsfr.min.css` par exemple).

En les retirant manuellement, on réduit le fichier de 7Ko.

J'imagine qu'il doit y avoir une option dans le build pour s'en passer, quitte à restaurer ensuite la version/licence si l'option était désactivée par défaut pour cette raison.

**Comment by lab9fr** [comment]
Bonjour David, 

Merci pour ce retour, nous sommes conscient de ce souci.

Il s'agit d'un problème de build qui demande de retravailler en profondeur le code pour s'assurer du bon ordre des différentes media-query. C'est pour le moment le work around que nous avons pu mettre en place pour s'en assurer. Nous avons une autre solution qui va se mettre en place sur le long terme.

Merci et bonne soirée
Cordialement
Bertrand, pour l'équipe DSFR
