### ISSUE TITLE
[Suggestion / Remarque] Comment puis-je intégrer les fichiers sources (scss) du DSFR dans un fichiers glue ?

### ISSUE THREAD

**Issue by pooley** [GouvernementFR/dsfr#634]
###  Suggestion
En lisant la doc je vois qu'il est possible d'ajouter les styles css en pointant les feuilles dans mon angular.json mais je ne vois nulle part la possibilité d'importer les sources *.scss vitales dans un glue _styles.scss_. (Par vitals, j'entends, variable, mixins et functions)

Dans mon projet je créé un template pour chaque feuille *.scss liée à son composant de la sorte : 

`// XS => 0 to 576px === @include respond-to(xs){}
// Default style goes here

///////////////////////////////// MEDIAQUERIES

// SM => 576px to 768px
@include respond-from(sm){}

// MD => 769px to 992px
@include respond-from(md){}

// LG => 993px to 1248px
@include respond-from(lg){}

// XL => 1248px and up
@include respond-from(xl){}`

Mais bien que mon IDE résolve son import par le nom et pas par import explicite de la partial, la compile ne passe pas. 
L'idée c'est de ne pas avoir à importer l'index des mediaqueries dans chaque composant 

`// import DSFR src
@import "@gouvfr/dsfr/module/media-query/index";`

ça fonctionne certes, mais j'aimerai plutôt de l'importer de façon unique directement dans mon fichier glue _style.scss_ listant toutes mes partials de styles (permet de pouvoir orchestrer l'ordre).

`// import DSFR src
@import "@gouvfr/dsfr/src/legacy", "@gouvfr/dsfr/src/main";

// import des partials de l'app
@import "styles/app-variables";
@import "styles/app-global";`  

Est-ce que j'ai loupé un truc ?

**Comment by lab9fr** [comment]
Bonjour @pooley,

La 1ere version du DSFR n'a pas été conçue avec cette idée en tête. C'est quelque chose qui va être retravaillé.

Merci pour ce retour
Bertrand, pour l'équipe DSFR

**Comment by pooley** [comment]
Merci pour ce retour Bertrand. Ça me rassure sur l'impossibilité avérée pour le moment. Je n'ai pas "loupé un truc" :)

Bonne continuation avec cette excellente initiative qu'est le dsfr.
