### ISSUE TITLE
`id` identiques sur les accordéons de la page "Périmètre d'application"

### ISSUE THREAD

**Issue by bellangerq** [GouvernementFR/dsfr#673]
###  Documentation associée
Ceela concerne la section "**Questions fréquentes**" de la page "[Périmètre d'application](https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/perimetre-d-application)".

Les 3 accordéons ont le même `id` et peu importe sur lequel on clique, c'est toujours le premier qui est ouvert.

###  Suggestion
Il faut modifier et rendre uniques les attributs suivants : 
- `aria-controls` de chaque `button.fr-accordion__btn`.
- `id` de chaque `div.fr-collapse`.

Et les lier correctement entre eux.

###  Sources (si applicable)
<img width="854" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/13785417/6dba360d-5082-4da9-81aa-5b774a3dca44">

**Comment by lab9fr** [comment]
Bonjour Quentin, 

Merci pour ce retour qui est maintenant corrigé

Bonne journée
Bertrand, pour l'équipe DSFR
