### ISSUE TITLE
Pagination: le selecteur css pour rendre un élément "actif" n'est pas suffisamment précis

### ISSUE THREAD

**Issue by MichaelBitard** [GouvernementFR/dsfr#677]
### Décrire le bug

Le selecteur css aria-current sur les éléments de pagination ne vérifie pas le contenu...

### Les étapes pour reproduire le bug
Exemple :
1. Créer un élément a --> `<a href="#" class="fr-pagination__link" aria-current="false">Lien</a>`
2. Ce lien ne devrait pas être "actif"

### Comportement attendu
Si aria-current="false" sur un élément de la pagination, alors le lien ne doit pas être actif

### Capture d’écran
![2023-07-05_16-51-39_grim](https://github.com/GouvernementFR/dsfr/assets/414642/14ffc67b-284e-466b-8a4d-281fb3896bc0)

### Configuration et système utilisé
- **Version du DSFR : 1.9.3**
- **Appareil (mobile, tablette, desktop) : All**
- **Navigateur et version : All **

**Comment by lab9fr** [comment]
Bonjour Michael,

Merci pour ce retour, nos équipes vont le traiter rapidement.

Bonne journée
Bertrand, pour l'équipe DSFR

**Comment by lab9fr** [comment]
Livraison prévue pour la 1.11
