### ISSUE TITLE
Variable non remplacée dans les fichiers de style compilés

### ISSUE THREAD

**Issue by pierre-isb** [GouvernementFR/dsfr#732]
### Décrire le bug
Le fichier dist/dsfr.css contient encore une variable sass, qui auraient dû être remplacée.
Pour simplifier l'utilisation des styles dans mon projet, on a fusionné nos feuilles de styles spécifiques et celles du dsfr en utilisant sass, qui nous a remonté l'erreur à la compilation. (cf. capture d'écran)

### Les étapes pour reproduire le bug
1. Importer le dsfr dans un fichier sass 
```sass
//styles.scss
@import "~@gouvfr/dsfr/dist/dsfr.css";

.mes-styles {}
```

2. transpiler le fichier sass 
```bash
$ sass styles.scss styles.css
```
### Comportement attendu
Toutes les variables sass devraient être remplacées par leur valeur une fois compilée

### Capture d’écran
![Capture d’écran 2023-08-17 à 14 32 53](https://github.com/GouvernementFR/dsfr/assets/55983581/f68ff40c-b7d5-4c6f-977a-175e6557863a)

### Configuration et système utilisé
- Version du DSFR : *1.10.0*

### Informations complémentaires
Concerne le style de `.fr-radio-group--sm input[type=radio]:checked:disabled + label`

**Comment by pierre-isb** [comment]
Je viens de mentionner un correctif, n'hésitez pas à le revoir :)
Bonne journée

**Comment by pierre-isb** [comment]
Bonjour,

Je me permets de relancer cette issue étant donné que le sujet nous bloque pour faire la montée de version et qu'elle entraîne une régression sur les radio-group.

Bonne journée

**Comment by lab9fr** [comment]
Bonjour Pierre, 

Nous avons effectivement repéré cette régression, elle est corrigée dans la PR #725 
Nous allons voir quand ce correctif peut être livré 

Merci de votre rapport et de la PR
Bertrand, pour l'équipe DSFR

**Comment by pierre-isb** [comment]
Bonjour,

Merci pour votre retour ! :)

Bonne fin de journée

**Comment by lab9fr** [comment]
livré dans la 1.10.1
