### ISSUE TITLE
Mise à jour du logo Twitter

### ISSUE THREAD

**Issue by J-Dudek** [GouvernementFR/dsfr#739]
**Si votre suggestion concerne un composant existant, merci de décrire le problème rencontré de façon claire et concise**
Sur le composant lien fr-link--twitter est-il possible/prévu une mise à jour du logo ?

**Décrivez le comportement souhaité**

Actuellement le logo est celui ci :
![image](https://github.com/GouvernementFR/dsfr/assets/46819368/6238c89b-6ecb-4643-a55a-6ac802ff2b18)
Depuis le 24 juillet le logo de X (anciennement Twitter) est celui-ci :
![image](https://github.com/GouvernementFR/dsfr/assets/46819368/62612968-e301-4b25-aadf-fb557f849c6a)

**Comment by lab9fr** [comment]
Bonjour Julien, 

Le nouveau logo twitter est maintenant à disposition sur la release 1.10.1 sortie hier.

Merci pour ce retour et bonne journée
Bertrand, pour l'équipe DSFR
