### ISSUE TITLE
Fournir un système de grille reposant sur les CSS grids à côté/à la place des flexboxes

### ISSUE THREAD

**Issue by christophehenry** [GouvernementFR/dsfr#764]
L'actuel système de grille reposant sur les flexboxes exige d'utiliser le squelette suivant :

```html
<div class="fr-container">
  <div class="fr-grid-row">
    <div class="fr-col-x"></div>
    <div class="fr-col-x"></div>
    <div class="fr-col-x"></div>
  </div>
  <div class="fr-grid-row">
    <div class="fr-col-x"></div>
    <div class="fr-col-x"></div>
    <div class="fr-col-x"></div>
  </div>
</div>
```

Le problème étant que ce squelette — en plus d'allourdir le HTML — s'adapte très mal avec les systèmes de template tel que Django où le contenu généré dans des boucles itératives, ne permet pas facilement de placer les `.fr-grid-row` intermédiaires.

**Décrivez le comportement souhaité**
Les CSS grids répondent beaucoup mieux à la génération itérative de contenu tout en permettant le même affichage en grilles. le DSFR devrait fournir à la place, ou en plus, d'un système de grille basé sur les flexboxes, un système de grille basé sur les grids.

**Comment by lab9fr** [comment]
Bonjour Christophe,

Merci pour cette suggestion, c'est quelque chose que nous envisageons pour la v2 du DSFR

Bertrand, pour l'équipe DSFR
