### ISSUE TITLE
a11y contraste couleurs - composants card

### ISSUE THREAD

**Issue by francoistibo** [GouvernementFR/dsfr#769]
Les tests de contraste couleur sur le composant card remontent des contrastes pas assez élevés sur certains éléments.
Ex ici : https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/carte/

Cela concerne tous les petits textes gris (sur fond blanc) présents dans les cards (cf capture écran).
![Capture d’écran 2023-09-06 à 15 27 51](https://github.com/GouvernementFR/dsfr/assets/280460/8430d4bf-8d70-4aa2-a267-f2da74f13a70)

Contrast constaté 4.23:1, alors qu'il est souhaité 4.5:1 minimum sur le RGAA 4 niveau AA.

Est-il possible de jouer sur la couleur et/oiu graisse et/ou taille de font pour que le contraste soit ok (supérieur à 4.5:1) ?

**Comment by lab9fr** [comment]
Bonjour François, 

Je pense qu'il y a eu une erreur dans le système que vous avez utilisé pour calculer le contraste.
Le système de couleur a été créé avec pour objectif d'offrir systématiquement des contrastes de luminance conforme au RGAA 4 niveau AA.

En l'occurrence, le rapport entre un texte mention #666 et un fond blanc #FFF amène un ratio de 5.74:1
<img width="1370" alt="Screenshot 2023-09-07 at 18 32 00" src="https://github.com/GouvernementFR/dsfr/assets/142149/1b6ec417-da96-43b7-b63d-42252752f669">

Comment avez-vous procédé pour effectuer ce calcul ?

Merci
Bertrand, pour l'équipe DSFR
