### ISSUE TITLE
fr-icon-user-setting-line - contenu du fichier svg correspondant à fr-icon-account-circle-line

### ISSUE THREAD

**Issue by n-langle** [GouvernementFR/dsfr#794]
### Décrire le bug
L'icône fr-icon-user-setting-line n'est pas la bonne. La déclaration est bien présente dans le fichier utility.css mais le svg contenu dans le fichier user-setting-line.svg correspond au fichier fr-icon-account-circle-line

### Comportement attendu
Que le contenu du fichier user-settings-line.svg soit corrigé

### Capture d’écran
<img width="826" alt="Capture d’écran 2023-09-20 à 10 27 55" src="https://github.com/GouvernementFR/dsfr/assets/28226882/4740746d-b3e8-40b2-aa3d-781c7b13055d">

<img width="429" alt="image" src="https://github.com/GouvernementFR/dsfr/assets/28226882/4cc283c1-8b75-488b-8731-d3efd3f08f39">

### Configuration et système utilisé
- **Version du DSFR :** 1.10.1

**Comment by lab9fr** [comment]
Bonjour @n-langle,

Merci pour ce retour, nos équipes traiter la problématique

Bertrand, pour l'équipe DSFR

**Comment by keryanS** [comment]
Correction apportée par la PR #797 livrée dans la version 1.11.0
