### ISSUE TITLE
Ajouter la possibilité de personalisé les breakpoints

### ISSUE THREAD

**Issue by tydoo** [GouvernementFR/dsfr#798]
Bonjour,

Pouvez vous ajouter la possibilité de personnaliser les breakpoints des medias queries.

Merci

**Comment by lab9fr** [comment]
Bonjour Thomas, 

Merci pour cette suggestion.
Le design du DSFR a été pensé pour fonctionner suivant les breakpoints que nous fournissons et il s'agit d'un manière d'encadrer l'usage des breakpoints, ce n'est donc aujourd'hui pas dans le périmètre des évolutions prévues.
Pour quel usage avez-vous besoin de personnaliser les breakpoints ?

Merci
Bertrand, pour l'équipe DSFR

**Comment by tydoo** [comment]
C'est pour un usage interne au ministère de l'Intérieur. 

Le souci c'est que vos breakPoint ne coïncide pas avec ceux de tailwindcss.

Ce qui fait que je suis obligé de les modifier manuellement dans les fichiers sans pouvoir les personnaliser définitivement tout en faisant les mises à jour via npm.

Je pense que ce serait utile tout en rebuildant le projet.

Merci

**Comment by lab9fr** [comment]
Tailwind permet de customiser ses breakpoints :  https://tailwindcss.com/docs/screens

C'est donc faisable dans l'autre sens :)

Notre but étant notamment d'harmoniser et  unifier le rendu des sites de l'état, on évite de laisser libre ce genre de customisation.
Merci
