### ISSUE TITLE
Variables CSS pour les points de ruptures

### ISSUE THREAD

**Issue by christophehenry** [GouvernementFR/dsfr#801]
En cherchant bien dans les fichiers CSS compilés, j'ai l'impression qu'il n'existe pas de variable CSS pour [les points de rupture documentés](https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/grille-et-points-de-rupture). Ça semble déclaré en dur dans le CSS. Ça serait pourtant des variables utilies à avoir sous le coude.

**Comment by comxd** [comment]
Les variables se trouvent dans le fichier `/src/core/style/selector/setting/_breakpoint.scss` :

```
$breakpoints: (
  xs: 0 35.98em,
  sm: 36em 47.98em,
  md: 48em 61.98em,
  lg: 62em 77.98em,
  xl: 78em,
) !default;
````


Exemple d'utilisation :

```
@media (min-width: nth(map_get($breakpoints, 'lg'), 1)) and (max-width: nth(map_get($breakpoints, 'lg'), 2)) {
        background-color: var(--background-active-blue-france);
}
```

**Comment by christophehenry** [comment]
Merci ! Ça devrait faire le travail en attendant.

**Comment by lab9fr** [comment]
Bonjour @christophehenry et @comxd,

Nous avons étudié la possibilité d'ajouter les breakpoints en custom prop, il y a même une PR dédiée #546 
Mais nous nous sommes demandé au final quelle pourrait être l'utilité de cet ajout au final.
Quel usage avez-vous de ces customs props ?

Merci et bonne journée
Bertrand pour l'équipe DSFR

**Comment by christophehenry** [comment]
Nous avons eu le cas d'éléments qui prennent une marge ou un style différent en fonction de la taille de l'écran.

**Comment by comxd** [comment]
C'est effectivement très rare, mais ça peut être pratique lorsqu'on souhaite cibler un breakpoint précis (exemple MD uniquement).

**Comment by lab9fr** [comment]
Merci pour vos réponses.

Pour les media queries, il ne me semble pas que l'on puisse utiliser les customs props (genre var(--bp-md-min)). 
Je saisis l'utilité des variables sass (et on les a mises à disposition), mais je n'arrive pas à voir de cas d'usage pour les custom props.
Vous auriez des cas à partager ?

Merci
Bertrand, pour l'équipe DSFR

**Comment by lab9fr** [comment]
Par ailleurs, pour insérer des media query avec nos points de reupture, vous pouvez directement utiliser les modules dédiés : 
```
@use 'module/media-query';

@include media-query.respond-from(md) {
  ...
}
```

**Comment by christophehenry** [comment]
Erf… Je connaissais pas cette limitation. Tant pis.

**Comment by lab9fr** [comment]
@comxd, un cas d'usage à partager ?

**Comment by comxd** [comment]
> Par ailleurs, pour insérer des media query avec nos points de reupture, vous pouvez directement utiliser les modules dédiés :
> 
> ```
> @use 'module/media-query';
> 
> @include media-query.respond-from(md) {
>   ...
> }
> ```

Merci Bertrand, je n'avais pas connaissance de cela.

Après une rapide analyze de notre côté, les cas où nous avons eu besoin d'accéder aux valeur des breakpoints porte sur des composants custom, en revanche nous avons eu plus souvent besoin d'avoir accès à ces valeurs via JavaScript mais l'API du DSFR permet cela facilement.

Cependant, la documentation du DSFR est insuffisante concernant son utilisation "bas niveau" via les APIs que ce soit SCSS ou JS, je pense que la partie [développeur](https://www.systeme-de-design.gouv.fr/utilisation-et-organisation/developpeurs) nécessite d'être complétée.

David D.
