### ISSUE TITLE
Ajouter une API JS pour rendre les liens des navigations et menus latéraux actives en fonction du scroll

### ISSUE THREAD

**Issue by christophehenry** [GouvernementFR/dsfr#814]
**Si votre suggestion concerne un composant existant, merci de décrire le problème rencontré de façon claire et concise**

Il peut arriver que les boutons de la navigation ou d'un menu latéral soient utilisés comme table des matières. Auquel cas, ils ne font pas référence à des pages mais à des sections dans la même page référencés par un fragment URI. 

Actuellement, la manière de rendre un bouton actuf est d'y ajouter `aria-current="page"`, ce qui suffit lorsque les liens font référence à des pages. Mais lorsque les liens font référence à la même page avec un fragment d'URI différent, il ne semble pas y avoir de méthode pour rendre le lien actif lorsque la page scrolle jusqu'à la section désignée par ce fragment.

**Si vous avez déjà identifié une correction**
[Bootstrap a une API qui permet ce comportement](https://getbootstrap.com/docs/5.3/components/scrollspy/). Il serait bien d'adopter une solution similaire.

**Comment by lab9fr** [comment]
Bonjour Christophe, 

Merci pour votre suggestion

C'est un comportement que nos équipes ont étudié et mis de côté, puisqu'actuellement, le composant menu latéral est destiné à une navigation entre pages, alors que c'est le sommaire qui permet une navigation entre différentes ancres dans une même page. Nous sommes en train d'étudier la mise en place du sommaire dans un encart latéral, nous verrons si nous pouvons introduire une manière d'indiquer l'élément actuel si ça va dans le sens de ce que l'on propose et réétudierons cette proposition.

Merci et bonne journée
Bertrand, pour l'équipe DSFR
