### ISSUE TITLE
Composant Transcription - Bouton "agrandir" NOK

### ISSUE THREAD

**Issue by misterdoak** [GouvernementFR/dsfr#820]
### Décrire le bug
En version 1.10.1, le bouton agrandir du composant transcription ne semble plus fonctionner.

Est-ce que vous reproduisez le même problème?

**Comment by lab9fr** [comment]
Bonjour Alain,

Je ne reproduis pas le problème sur la v1.10.1 : https://v1-10-1--ds-gouv.netlify.app/example/component/transcription/
à mois que ce soit sur un OS et/ou navigateur particulier ?

Merci
Bertrand pour l'équipe DSFR

**Comment by misterdoak** [comment]
Bonjour,

C'est bon pour moi.
Par contre, j'ai l'impression que la documentation est pas super à jour sur le sujet. Le positionnement sur bouton "Agrandir" pas au même endroit notamment.

Merci d'avoir regardé!

Alan

**Comment by keryanS** [comment]
- Bug non reproduit
- Mise à jour de la doc transcription réalisée en v1.11.0
