### ISSUE TITLE
Update Documentation example according to 1.11.0 evolutions

### ISSUE THREAD

**Issue by cfieux** [GouvernementFR/dsfr#849]
###  Documentation associée
[README.md](https://github.com/GouvernementFR/dsfr/blob/main/README.md) / https://github.com/GouvernementFR/dsfr?tab=readme-ov-file#le-html and possibly others ?

###  Suggestion
meta tag still doesn't include additionnal attributes indicated in the release notes

```markdown
  ajouter dans le head : <meta name="format-detection" content="telephone=no,date=no,address=no,email=no,url=no">
```

###  Sources (si applicable)
https://github.com/GouvernementFR/dsfr/releases/tag/v1.11.0

**Comment by keryanS** [comment]
Bonjour,

Merci pour le retour, une correction a été apporté.
