### ISSUE TITLE
Border sur les Contrôle segmenté et les toggle bug avec Firefox

### ISSUE THREAD

**Issue by tydoo** [GouvernementFR/dsfr#892]
Les Contrôle segmenté et les toggle ont un border inégale avec Firefox.

Je n'ai pas ce probléme avec Chrome 122.0.6261.70.

![image](https://github.com/GouvernementFR/dsfr/assets/50534204/e66699e5-85c5-48dd-ad1e-6c80f566e054)
![image](https://github.com/GouvernementFR/dsfr/assets/50534204/0b75b27f-6093-4216-9bd3-8a4d8e2774a1)

Version de firefox : 115.8.0esr.
Version du DSFR : 1.11.1

**Comment by keryanS** [comment]
Bonjour,

Il s'agit d'un bug du rendu des box-shadow de Firefox.
Une issue est ouverte de leur coté : https://bugzilla.mozilla.org/show_bug.cgi?id=1888332

Je ferme celle-ci, car ce n'est pas de notre ressort.
En v2, si cela n'est toujours pas corrigé, nous réfléchirons à une autre manière de dessiner ces bordures.

keryan,
_pour l'équipe DSFR_

**Comment by tydoo** [comment]
@keryanS Possible de réouvrir ?

En version 128 ESR de Firefox qui viens de sortir, on a toujours le même problème.

Et le ticket chez Mozilla est également toujours ouvert.!

Merci
