### ISSUE TITLE
Prise en charge de l'attribut readonly

### ISSUE THREAD

**Issue by kolok** [GouvernementFR/dsfr#919]
l'attribut `readonly` se comporte comme l'attribut `disabled` à ceci près que la valeur du champs est envoyé lors de la soumission du formulaire.

En terme d'affichage, les champs de saisie devraient s'afficher de la même manière que les champs de saisie avec l'attribut `disabled`

L'attribut read-only est pris en charge par tous les navigateurs communs : [https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/readonly)

Qu'en pensez vous ?

**Comment by keryanS** [comment]
Bonjour,
Nous nous conformons au comportement standard des navigateurs, qui est de ne pas styliser de manière différente les champs en readonly : 

**Chrome**
readonly:
![image](https://github.com/GouvernementFR/dsfr/assets/2979634/c8355e1f-1ac0-4f68-abf2-8b1d0fb12812)

vs [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#examples):

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/dbb127b4-337e-42d6-ab22-4f79ab860d47)

**Firefox**
readonly:

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/41e2acc5-5378-44f1-9101-4f1987f19c08)
vs [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#examples):

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/4fc1597b-692b-4cd4-8120-be6d0240936d)


**Safari**
readonly:

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/232926f7-187a-4e81-8883-b1743a5cb105)

vs [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#examples):

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/adc5ed70-a844-4de1-8125-5366da2decaf)

**Edge**
readonly:

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/a5b9e468-f1c0-4ff2-8779-c3ab9e1690d3)

vs [disabled](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/disabled#examples):

![image](https://github.com/GouvernementFR/dsfr/assets/2979634/1f8d3c10-480b-4c93-95fd-1bef7388b6ec)
