### ISSUE TITLE
[input] Manque le style CSS pour message warning

### ISSUE THREAD

**Issue by edugouvfr** [GouvernementFR/dsfr#934]
### Décrire le bug
Concernant le style CSS pilotant l'aspect des messages associés au champs de formulaire, il est actuellement possible d'utiliser les classes `fr-message--error`, `fr-message--valid`, `fr-message--info` mais la classe `fr-message--warning` n'est pas disponible.

Étant donné que cette possibilité existe bien côté Figma il semble que ce soit juste un oubli côté dev.

cf. [fil de discussion Slack](https://gouvfr.slack.com/archives/C012RFYSRCG/p1711728999378009)

### Comportement attendu
La classe CSS `fr-message--warning` devrait être disponible

### Configuration et système utilisé
- **Version du DSFR : 1.11.2 **

**Comment by keryanS** [comment]
Nous ne sommes pas convaincus de l'intérêt de l'implémenter, hors cas très particulier, cela pourrait causer plus de mauvaises utilisations que d'usages légitimes rares.

Nous réfléchirons en v2 à sa réintégration.

Après techniquement... il est possible d'utiliser les classes utilitaires pour simuler ce comportement : 
class="fr-text--sm fr-text-default--warning fr-icon-warning-fill fr-icon--sm" :shushing_face:
