### ISSUE TITLE
Pas de loader dans les composants ?

### ISSUE THREAD

**Issue by christophehenry** [GouvernementFR/dsfr#939]
Il se semble pas y avoir de  [loader (indicateur de progrès)](https://m3.material.io/components/progress-indicators/overview) parmis [les composants du DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface). Cela semble pourtant un composant important pour indiquer une requête HTML en cours.

**Comment by comxd** [comment]
Je suis persuadé de l'avoir vu dans la roadmap à un moment donné mais il semble avoir été supprimé...

**Comment by keryanS** [comment]
Bonjour,
En effet, le composant a été dépriorisé.

Keryan, 
_pour l'équipe du DSFR_
