### ISSUE TITLE
Clignotement au chargement de la page lorsque le dark mode est sélectionné

### ISSUE THREAD

**Issue by Thommusa** [GouvernementFR/dsfr#960]
### Décrire le bug
Lorsqu'on utilise le composant "Paramètre d'affichage" et que l'on se met en dark mod, un clignotement blanc au chargement de la page est perceptible.
Le bug peut être observé sur votre propre site : https://www.systeme-de-design.gouv.fr
Le bug n'est pas présent sur les sites que vous cité en exemple : 
https://www.defense.gouv.fr
### Les étapes pour reproduire le bug
Exemple :
1. Inclure la librairie DSFR
2. Utiliser le composant "Paramètre d'affichage"
3. Passer en mode dark theme
4. Recharger la page
5. Observer le clignotement en blanc puis noir de la page (se mettre en débit réduit du navigateur pour mieux observer)

### Configuration et système utilisé
- **Version du DSFR :  1.10**

**Comment by keryanS** [comment]
Bonjour,
Il existe un script à ajouter au début du contenu qui permet d'éviter ce clignotement : 
[https://main--ds-gouv.netlify.app/example/scheme/](https://main--ds-gouv.netlify.app/example/scheme/
)
Keryan Sanié, pour l'équipe DSFR.

**Comment by Thommusa** [comment]
bonjour, merci pour la réponse. Juste pour savoir pourquoi ces lignes ne sont pas inclues directement dans la librairie ?
