### ISSUE TITLE
Liens morts sur la page « versions précédentes »

### ISSUE THREAD

**Issue by thibault** [GouvernementFR/dsfr#965]
Hello,

###  Documentation associée

Sur la page « versions précédentes », il semble que tous les liens permettant de consulter les notes de versions soient morts.

https://www.systeme-de-design.gouv.fr/a-propos/versions/versions-precedentes/

Par exemple, le lien vers la « Note de version » pour la v1.10 pointent vers une 404 :

https://www.systeme-de-design.gouv.fr/a-propos/versions/version-1-10

###  Suggestion

Pas vraiment de suggestion, à part permettre de consulter les anciennes notes de version.

**Comment by johanricher** [comment]
Le call to action "Prendre en main le Système de Design" sur la page d'accueil est cassé également :

[Screencast from 2024-07-01 14-53-19.webm](https://github.com/GouvernementFR/dsfr/assets/10212787/91ecb9a9-2b78-437f-8ca6-b1a55fa63caf)

**Comment by keryanS** [comment]
Bonjour,
C'est bien noté, nous allons corriger cela.
