### ISSUE TITLE
Erreur "Invalid media query" avec cypress

### ISSUE THREAD

**Issue by iNeoO** [GouvernementFR/dsfr#974]
### Décrire le bug
dans `module/legacy/mixin/_legacy.scss` depuis https://github.com/GouvernementFR/dsfr/commit/71d21990b615d23fb5ca30d81caaf58b6c8e4ff3 
Le hack `@media screen and (min-width:0\0) and (min-resolution:+72dpi) {`

fait planter cypress

ce qui casse les tests de https://github.com/dnum-mi/vue-dsfr

### Les étapes pour reproduire le bug
Lancer cypress avec le dsfr

### Comportement attendu
Est ce qu'il serait possible de rollback ce hack ?

### Capture d’écran
![An uncaught error was detected outside of a test (failed)](https://github.com/GouvernementFR/dsfr/assets/8982189/b326c255-1d22-4d6e-b98d-980f3ca72894)

### Configuration et système utilisé
- **Version du DSFR : ** 1.12.1
- **Version de cypress : ** 13.13.0

**Comment by keryanS** [comment]
Bonjour,
Ce hack permet de cibler Internet Explorer.
Le précédent utilisait la propriété "ms-constrast: active", le problème est qu'elle s'exécutait avec le Windows High Contrast Mode.
Avez-vous la possibilité de désactiver la règle lint [media-feature-name-value-no-unknown](https://stylelint.io/user-guide/rules/media-feature-name-value-no-unknown)
Ou d'y ajouter une règle d'ignore ciblée sur ce hack ignoreMediaFeatureNames ?
